"""Weetjes voor pagina 900-909. Elke categorie krijgt een eigen pagina."""

WEETJES = [
    ("DIEREN", [
        "Een octopus heeft drie harten en blauw bloed.",
        "Een giraf heeft evenveel nekwervels als een mens: zeven.",
        "Flamingo's zijn roze door de kleurstoffen in de garnaaltjes en algen die ze eten.",
        "Zeeotters houden elkaars poot vast tijdens het slapen, zodat ze niet van elkaar wegdrijven.",
        "Een kolibrie kan als enige vogel echt achteruit vliegen.",
        "Het hart van een blauwe vinvis weegt ongeveer 180 kilogram.",
        "Vlinders proeven met hun poten.",
        "Haaien bestaan al langer dan bomen.",
        "Een wombat maakt kubusvormige keutels.",
        "Spinnenzijde is, gewicht voor gewicht, sterker dan staal.",
        "Een eendagsvlieg leeft als larve tot twee jaar onder water, maar als volwassen insect vaak maar een dag.",
    ]),
    ("RUIMTE", [
        "Een dag op Venus duurt langer dan een jaar op Venus.",
        "Zonlicht doet ongeveer 8 minuten en 20 seconden over de reis naar de aarde.",
        "De voetafdrukken van de Apollo-astronauten staan nog op de maan: er is geen wind om ze uit te wissen.",
        "Alle andere planeten van ons zonnestelsel samen passen in Jupiter.",
        "Een theelepel materie van een neutronenster weegt miljarden tonnen.",
        "Het ruimtestation ISS draait ongeveer elke 90 minuten rond de aarde.",
        "Saturnus heeft een lagere gemiddelde dichtheid dan water.",
        "De hoogste vulkaan van het zonnestelsel is Olympus Mons op Mars: ongeveer 22 kilometer hoog.",
        "Dirk Frimout werd in 1992 de eerste Belg in de ruimte.",
        "De Belgische priester Georges Lemaître stelde in 1927 als eerste voor dat het heelal uitdijt.",
    ]),
    ("MENS & LICHAAM", [
        "Een baby wordt geboren met ongeveer 300 botjes; een volwassene heeft er 206, omdat er botten vergroeien.",
        "Je hart klopt ongeveer 100.000 keer per dag.",
        "Vingerafdrukken zijn uniek, zelfs bij eeneiige tweelingen.",
        "Je hersenen verbruiken ongeveer 20 procent van de energie van je lichaam.",
        "Je bent 's ochtends ongeveer een centimeter groter dan 's avonds.",
        "Het dijbeen is het langste en sterkste bot van je lichaam.",
        "Tandglazuur is het hardste materiaal in het menselijk lichaam.",
        "Een volwassene heeft ongeveer 5 liter bloed.",
        "Je knippert ongeveer 15 tot 20 keer per minuut met je ogen.",
        "Je kan niet tegelijk ademen en slikken.",
    ]),
    ("BELGIË", [
        "De saxofoon werd rond 1840 uitgevonden door Adolphe Sax uit Dinant.",
        "Het Atomium werd gebouwd voor Expo 58 en stelt een ijzerkristal voor, 165 miljard keer vergroot.",
        "België heeft drie officiële talen: Nederlands, Frans en Duits.",
        "Kuifje verscheen voor het eerst in 1929, getekend door de Brusselaar Hergé.",
        "De Smurfen werden in 1958 bedacht door de Belgische tekenaar Peyo.",
        "In 1835 reed tussen Brussel en Mechelen de eerste passagierstrein van het Europese vasteland.",
        "België voerde in 1893 de opkomstplicht bij verkiezingen in, een van de oudste ter wereld.",
        "Jean Neuhaus vond in 1912 in Brussel de gevulde chocoladebonbon uit: de praline.",
        "Manneken Pis heeft meer dan duizend kostuums.",
        "Het hoogste punt van België is het Signal de Botrange: 694 meter.",
        "De warmste temperatuur ooit in België werd gemeten in Begijnendijk: 41,8 graden op 25 juli 2019.",
    ]),
    ("GESCHIEDENIS", [
        "De Grote Piramide van Gizeh was bijna 3.800 jaar lang het hoogste bouwwerk ter wereld.",
        "Cleopatra leefde dichter bij de maanlanding dan bij de bouw van de Grote Piramide.",
        "De Slag bij Waterloo vond plaats op 18 juni 1815, net ten zuiden van Brussel.",
        "De Berlijnse Muur viel op 9 november 1989.",
        "De eerste moderne Olympische Spelen vonden plaats in Athene in 1896.",
        "Antwerpen organiseerde de Olympische Spelen van 1920.",
        "De universiteit van Oxford is ouder dan het Azteekse rijk.",
        "Gutenberg bracht rond 1450 de boekdrukkunst met losse letters naar Europa.",
        "Neil Armstrong zette op 21 juli 1969 (Belgische tijd) als eerste mens voet op de maan.",
        "De eerste teletekstdienst, Ceefax, startte in 1974 in het Verenigd Koninkrijk.",
    ]),
    ("TAAL", [
        "Het woord 'robot' komt uit het Tsjechisch: robota betekent dwangarbeid.",
        "Het woord 'gas' werd bedacht door de Brusselse scheikundige Jan Baptist van Helmont.",
        "Het Engelse 'cookie' komt van het Nederlandse 'koekje'.",
        "Het Engelse 'yacht' komt van het Nederlandse 'jacht'.",
        "Nederlands is een officiële taal in België, Nederland, Suriname, Aruba, Curaçao en Sint-Maarten.",
        "Hendrik Consciences 'De Leeuw van Vlaenderen' verscheen in 1838.",
        "Kuifje heet in het Frans Tintin en in het Engels ook Tintin.",
        "Het Afrikaans in Zuid-Afrika is ontstaan uit het Nederlands van de 17e eeuw.",
        "Het woord 'Brussel' komt van 'broek-zele': woning in het moeras.",
    ]),
    ("NATUUR & AARDE", [
        "Ongeveer 71 procent van het aardoppervlak is bedekt met water.",
        "De Marianentrog is bijna 11 kilometer diep.",
        "Een bliksemschicht is ongeveer vijf keer heter dan het oppervlak van de zon.",
        "De grootste woestijn ter wereld is Antarctica, niet de Sahara.",
        "Sommige soorten bamboe groeien bijna een meter per dag.",
        "Er staan meer bomen op aarde dan er sterren zijn in de Melkweg.",
        "De Amazone voert meer water af dan de zeven volgende grootste rivieren samen.",
        "De Mount Everest wordt nog elk jaar een paar millimeter hoger.",
        "Een kwart van alle diersoorten die we kennen, is een kever.",
    ]),
    ("RECORDS", [
        "Het hoogste gebouw ter wereld is de Burj Khalifa in Dubai: 828 meter.",
        "De langste spoortunnel ter wereld is de Gotthard-basistunnel in Zwitserland: 57 kilometer.",
        "De Chinese Muur is vanuit de ruimte niet met het blote oog te zien.",
        "Usain Bolt liep in 2009 de 100 meter in 9,58 seconden.",
        "Eddy Merckx won vijf keer de Tour de France.",
        "Vaticaanstad is het kleinste land ter wereld: ongeveer een halve vierkante kilometer.",
        "Rusland is het grootste land ter wereld: bijna twee keer zo groot als Canada.",
        "Kim Clijsters en Justine Henin stonden allebei nummer één op de wereldranglijst tennis.",
    ]),
    ("UITVINDINGEN", [
        "De eerste sms werd in 1992 verstuurd: 'Merry Christmas'.",
        "Het world wide web werd in 1989 bij CERN bedacht door Tim Berners-Lee, samen met de Belg Robert Cailliau.",
        "De Belg Leo Baekeland vond in 1907 bakeliet uit, het eerste volledig synthetische plastic.",
        "De Belg Zénobe Gramme bouwde rond 1870 de eerste bruikbare dynamo.",
        "Penicilline werd in 1928 per toeval ontdekt door Alexander Fleming.",
        "De magnetron werd uitgevonden nadat een chocoladereep smolt in de broekzak van een radaringenieur.",
        "De post-it ontstond uit een mislukte poging om superlijm te maken.",
        "De eerste computermuis, uit de jaren 60, was gemaakt van hout.",
    ]),
]
